const express=require("express")
const router=express.Router()
const authmiddleware=require("../middleware")
const signupRouter=require("./signup")
const signinRouter=require("./signin")
const foodItemRouter=require("./foodcontroller")
const beautysalonRouter=require("./saloncontroller")
const fitnessRouter=require("./fitnesscontroller")
const stationeryRouter=require("./stationerycontroller")
const partyhallRouter=require("./partyhallcontroller")
const movieticketRouter=require("./movieticketcontroller")
const AllItemsRouter=require("./AllItems")
const cartRouter=require("./cartcontroller")

router.use("/signup",signupRouter)
router.use("/signin",signinRouter)
router.use(authmiddleware)
router.use("/admin/foodcontroller",foodItemRouter)
router.use("/admin/saloncontroller",beautysalonRouter)
router.use("/admin/fitnesscontroller",fitnessRouter)
router.use("/admin/stationerycontroller",stationeryRouter)
router.use("/admin/partyhallcontroller",partyhallRouter)
router.use("/admin/movieticketcontroller",movieticketRouter)
router.use("/user/AllItems",AllItemsRouter)
router.use("/user/cartcontroller",cartRouter)
router.use("/user/cartcontroller",cartRouter)
router.use("/user/cartcontroller",cartRouter)
router.use("/user/cartcontroller",cartRouter)
router.use("/user/cartcontroller",cartRouter)
router.use("/user/cartcontroller",cartRouter)
module.exports=router